name: Build PyTorch3D Wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Match your target version

      # Install build dependencies
      - name: Install build tools
        run: |
          pip install wheel cibuildwheel==2.16.2  # <button class="citation-flag" data-index="2"><button class="citation-flag" data-index="3">
          # Install Microsoft Build Tools if needed
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

      # Build wheels using cibuildwheel
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: |
            pip install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
            pip install -r requirements.txt
            git clone -b v0.6.1 https://github.com/facebookresearch/pytorch3d.git
          CIBW_BUILD: "cp38-win_amd64"  # Python 3.8 Windows x64
          CIBW_ENVIRONMENT: |
            MMCV_WITH_OPS=1
            FORCE_MLU=1
          CIBW_BEFORE_BUILD_WINDOWS: |
            conda install -c conda-forge ffmpeg  # If conda is required
        run: |
          cibuildwheel --output-dir wheelhouse
        shell: cmd

      # Upload artifacts
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: pytorch3d-wheels
          path: wheelhouse/*.whl
